// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6vui-3g3xtzXp16vlXogHyBxMw1bL-uA',
    appId: '1:1065469951413:web:2489c6a4d47b2f624dedfc',
    messagingSenderId: '1065469951413',
    projectId: 'project-44994',
    authDomain: 'project-44994.firebaseapp.com',
    storageBucket: 'project-44994.appspot.com',
    measurementId: 'G-Z4V8EQ9ME3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcYdozjA1wcCEWtbIiMlGLkQQ-5ttMVAw',
    appId: '1:1065469951413:android:a69e21ec4919ad7a4dedfc',
    messagingSenderId: '1065469951413',
    projectId: 'project-44994',
    storageBucket: 'project-44994.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVDvS90Jr75YvyISXcap9VRfxKZAh90ok',
    appId: '1:1065469951413:ios:4f9b39517e25ed7c4dedfc',
    messagingSenderId: '1065469951413',
    projectId: 'project-44994',
    storageBucket: 'project-44994.appspot.com',
    iosBundleId: 'com.example.it14Project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVDvS90Jr75YvyISXcap9VRfxKZAh90ok',
    appId: '1:1065469951413:ios:c2ecbfc04b23d6074dedfc',
    messagingSenderId: '1065469951413',
    projectId: 'project-44994',
    storageBucket: 'project-44994.appspot.com',
    iosBundleId: 'com.example.it14Project.RunnerTests',
  );
}
